on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy with node version ${{ matrix.node_version }} on Vercel
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['20.x']
        os: ['ubuntu-22.04']
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install
      run: npm install
    - name: Build
      run: npm run build
    
